# Generated by Django 3.0.7 on 2020-06-20 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestampt',
            new_name='timestamp',
        ),
    ]
